name: Events Demo 1
on:
  pull_request:
    types: # we can define type of event trigger 
      - opened
      # - closed
    branches:
      - main
      # - dev
      # - 'dev-*'
      # - 'feat/**'
  workflow_dispatch: # Also can add multiple type of event trigger in this format
  push:
    branches:
      - main
      # - dev
      # - 'dev-*'
      # - 'feat/**'
    # paths: # it will trigger if a push or pull_request changes files in specifc path
    #   - '**.js'
    paths-ignore: # it will trigger if we did not change a file in specific path below
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."